# Generated by Django 3.1.7 on 2021-03-31 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210330_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Название категории'),
        ),
        migrations.AlterField(
            model_name='news',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(max_length=200, upload_to='photos/%Y/%m/%d/', verbose_name='Расположение фото'),
        ),
    ]
